gerhgr

diff --git a/.github/workflows/test_code_quality_pull_request.yml b/.github/workflows/test_code_quality_pull_request.yml
--- a/.github/workflows/test_code_quality_pull_request.yml
+++ b/.github/workflows/test_code_quality_pull_request.yml
@@ -20,7 +20,7 @@ jobs:
         pip install sqlfluff
     - name: Check style of the code (Python)
       run: |
-          flake8 > flake8_output.txt 2>&1 || echo "flake8 Errors detected"
+          flake8 > flake8_output.txt 2>&1 || echo "FLAKE8_FAILED=1" >> $GITHUB_ENV
           if [ -s flake8_output.txt ]; then
             echo "FLAKE8_FAILED=1" >> $GITHUB_ENV
           fi
@@ -41,7 +41,7 @@ jobs:
       run: cat bandit_output.txt
     - name: Check style of the code (SQL)
       run: |
-          sqlfluff lint **/*.sql > sqlfluff_output.txt 2>&1 || echo "SQLFLUFF_FAILED=1" >> $GITHUB_ENV
+          find . -name '*.sql' -print0 | xargs -0 sqlfluff lint > sqlfluff_output.txt 2>&1 || echo "SQLFLUFF_FAILED=1" >> $GITHUB_ENV
     - name: Display style problem if any (SQL)
       if: env.SQLFLUFF_FAILED == '1'
       run: cat sqlfluff_output.txt
