try

diff --git a/.github/workflows/test_code_quality.yml b/.github/workflows/test_code_quality.yml
--- a/.github/workflows/test_code_quality.yml
+++ b/.github/workflows/test_code_quality.yml
@@ -15,6 +15,7 @@ jobs:
     - name: Install flake8
       run: pip install flake8
     - name: Run flake8
-      run: flake8 . --max-line-length 120 --show-source
-
-      continue-on-error: false
+      run: flake8 . || (echo "Errors detected" && flake8 . > flake8_output.txt)
+    - name: Display flake8 errors if any
+      if: failure()
+      run: cat flake8_output.txt
