try

diff --git a/.github/workflows/test_code_quality.yml b/.github/workflows/test_code_quality.yml
--- a/.github/workflows/test_code_quality.yml
+++ b/.github/workflows/test_code_quality.yml
@@ -6,45 +6,44 @@ jobs:
   code-check:
     runs-on: ubuntu-latest
     steps:
-    - name: Check out repository code
-      uses: actions/checkout@v2
+    - name: Checkout
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
+
+    - name: Get changed files
+      id: changed-files
+      run: |
+        if [ "${{ github.event_name }}" == "pull_request" ]; then
+          changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep '\.py$' | xargs)
+          echo "changed_files=$changed_files" >> $GITHUB_ENV
+        else
+          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.py$' | xargs)
+          echo "changed_files=$changed_files" >> $GITHUB_ENV
+
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.x'
+
     - name: Install flake8 and Bandit
       run: |
         pip install flake8
         pip install bandit
-    - name: Get changed Python files for pull request
-      id: files
+
+    - name: Run flake8
+      if: env.changed_files
       run: |
-        if git rev-parse HEAD^ > /dev/null 2>&1; then
-          git diff --name-only HEAD^ HEAD | grep '\.py$' > changed_files.txt
-        else
-          git diff --name-only HEAD | grep '\.py$' > changed_files.txt
-        fi
-        if [ -s changed_files.txt ]; then
-          echo "::set-output name=files::$(cat changed_files.txt)"
-        else
-          echo "::set-output name=files::"
-        fi
-    - name: Run flake8 on changed files
+        flake8 $changed_files > flake8_output.txt 2>&1 || echo "flake8 Errors detected"
+    - name: Run Bandit
+      if: env.changed_files
       run: |
-        if [ -n "${{ steps.files.outputs.files }}" ]; then
-          flake8 ${{ steps.files.outputs.files }} > /dev/null 2>&1 || (echo "flake8 Errors detected" && flake8 ${{ steps.files.outputs.files }} > flake8_output.txt)
-        fi
-    - name: Run Bandit on changed files
-      run: |
-        if [ -n "${{ steps.files.outputs.files }}" ]; then
-          bandit -r ${{ steps.files.outputs.files }} -o bandit_output.txt
-        fi
-    - name: Display Code Quality or Style errors if any
-      if: failure()
+        bandit -r $changed_files -o bandit_output.txt || echo "Bandit Issues detected"
+
+    - name: Display flake8 errors if any
+      if: failure() && steps.changed-files.outputs.changed_files
       run: cat flake8_output.txt
-    - name: Display Security errors if any
-      if: always()
-      run: |
-        if [ -s bandit_output.txt ]; then
-          cat bandit_output.txt
-        fi
+
+    - name: Display Bandit issues if any
+      if: failure() && steps.changed-files.outputs.changed_files
+      run: cat bandit_output.txt
