try

diff --git a/.github/workflows/test_code_quality.yml b/.github/workflows/test_code_quality.yml
--- a/.github/workflows/test_code_quality.yml
+++ b/.github/workflows/test_code_quality.yml
@@ -42,10 +42,7 @@ jobs:
     - name: Run Bandit and set failure flag
       if: env.changed_files
       run: |
-          bandit -r $changed_files -o bandit_output.txt || echo "flake8 Errors detected"
-          if [ -s bandit_output.txt ]; then
-            echo "BANDIT_FAILED=1" >> $GITHUB_ENV
-          fi
+          bandit -r $changed_files -o bandit_output.txt || echo "BANDIT_FAILED=1" >> $GITHUB_ENV
   
     - name: Display Bandit errors if any
       if: env.BANDIT_FAILED == '1'
