up

diff --git a/.github/workflows/test_code_quality_push.yml b/.github/workflows/test_code_quality_push.yml
--- a/.github/workflows/test_code_quality_push.yml
+++ b/.github/workflows/test_code_quality_push.yml
@@ -39,7 +39,20 @@ jobs:
     - name: Display style problem if any
       if: env.FLAKE8_FAILED == '1'
       run: cat flake8_output.txt
-  
+
+
+    - name: Check quality of the code
+      if: env.changed_files
+      run: |
+          pylint $changed_files > pylint_output.txt 2>&1 || echo "pylint Errors detected"
+          if [ -s pylint_output.txt ]; then
+            echo "PYLINT_FAILED=1" >> $GITHUB_ENV
+          fi
+
+    - name: Display problem of quality if any
+      if: env.PYLINT_FAILED == '1'
+      run: cat pylint_output.txt
+
     - name: Check security problem
       if: env.changed_files
       run: |
@@ -50,5 +63,5 @@ jobs:
       run: cat bandit_output.txt
 
     - name: Check if Action need to fail
-      if: env.BANDIT_FAILED=='1' || env.FLAKE8_FAILED=='1'
+      if: env.BANDIT_FAILED=='1' || env.FLAKE8_FAILED=='1' || env.PYLINT_FAILED=='1'
       run: exit 1
